name = "npmtrends-presets"
compatibility_date = "2025-08-01"

# Workers main entry point
main = "src/index.ts"

# Static assets
[assets]
directory = "./dist"
binding = "ASSETS"

# D1 バインド
[[d1_databases]]
binding = "DB"
database_name = "trends_list"
database_id = "e8421c53-4224-4813-a75e-2eb51dd40506"

# KV（任意：ランキングキャッシュ）
[[kv_namespaces]]
binding = "KV"
id = "ec8459f713824fbb9b288f7bf0721165"

# シークレットに入れる（wrangler secret put コマンドで設定）
# TURNSTILE_SECRET_KEY
# CLERK_SECRET_KEY

# Cron triggers for scheduled tasks
[triggers]
crons = ["0 2 * * *"]  # 毎日午前2時に実行（UTC）

[vars]
TURNSTILE_SITE_KEY = "0x4AAAAAABqcBHFWD4wypzFb"
CLERK_PUBLISHABLE_KEY = "pk_test_YWNjZXB0ZWQtc29sZS04OS5jbGVyay5hY2NvdW50cy5kZXYk"
# Development environment
[env.development]